#!/bin/bash

#
#   @file    remove_cmake_install.sh
#   @author  Jiri Fajtl, <ok1zjf@gmail.com>
#   @date    13/7/2015
#   @version 0.1
# 
#   @brief Deletes all files reffered by install_manifest.txt
#	which is generated by
#	$ make install
# 
#

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DAR_ROOT=$(dirname $SCRIPT_DIR)

cat install_manifest.txt | while read f; do rm "$f"; done

